# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'findFrameMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 420))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sliderMatchThresh = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderMatchThresh.sizePolicy().hasHeightForWidth())
        self.sliderMatchThresh.setSizePolicy(sizePolicy)
        self.sliderMatchThresh.setMinimum(1)
        self.sliderMatchThresh.setMaximum(99)
        self.sliderMatchThresh.setSliderPosition(10)
        self.sliderMatchThresh.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMatchThresh.setInvertedAppearance(False)
        self.sliderMatchThresh.setObjectName("sliderMatchThresh")
        self.gridLayout.addWidget(self.sliderMatchThresh, 2, 1, 1, 1)
        self.progressMatch = QtWidgets.QProgressBar(self.centralwidget)
        self.progressMatch.setMinimumSize(QtCore.QSize(0, 0))
        self.progressMatch.setMaximumSize(QtCore.QSize(12, 16777215))
        self.progressMatch.setAutoFillBackground(False)
        self.progressMatch.setStyleSheet("")
        self.progressMatch.setProperty("value", 0)
        self.progressMatch.setTextVisible(False)
        self.progressMatch.setOrientation(QtCore.Qt.Vertical)
        self.progressMatch.setObjectName("progressMatch")
        self.gridLayout.addWidget(self.progressMatch, 4, 8, 3, 1)
        self.btnResults = QtWidgets.QPushButton(self.centralwidget)
        self.btnResults.setMinimumSize(QtCore.QSize(0, 32))
        self.btnResults.setObjectName("btnResults")
        self.gridLayout.addWidget(self.btnResults, 3, 7, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.fieldVideo = QtWidgets.QLineEdit(self.centralwidget)
        self.fieldVideo.setObjectName("fieldVideo")
        self.gridLayout.addWidget(self.fieldVideo, 1, 1, 1, 6)
        self.textLog = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLog.sizePolicy().hasHeightForWidth())
        self.textLog.setSizePolicy(sizePolicy)
        self.textLog.setMinimumSize(QtCore.QSize(0, 0))
        self.textLog.setFrameShape(QtWidgets.QFrame.Panel)
        self.textLog.setUndoRedoEnabled(False)
        self.textLog.setReadOnly(True)
        self.textLog.setObjectName("textLog")
        self.gridLayout.addWidget(self.textLog, 3, 0, 4, 2)
        self.imageVideoFrame = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageVideoFrame.sizePolicy().hasHeightForWidth())
        self.imageVideoFrame.setSizePolicy(sizePolicy)
        self.imageVideoFrame.setMinimumSize(QtCore.QSize(180, 120))
        self.imageVideoFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.imageVideoFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageVideoFrame.setText("")
        self.imageVideoFrame.setScaledContents(False)
        self.imageVideoFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.imageVideoFrame.setObjectName("imageVideoFrame")
        self.gridLayout.addWidget(self.imageVideoFrame, 4, 5, 1, 3)
        self.progressMatchPeak = QtWidgets.QProgressBar(self.centralwidget)
        self.progressMatchPeak.setMinimumSize(QtCore.QSize(0, 0))
        self.progressMatchPeak.setMaximumSize(QtCore.QSize(12, 16777215))
        self.progressMatchPeak.setProperty("value", 0)
        self.progressMatchPeak.setTextVisible(False)
        self.progressMatchPeak.setOrientation(QtCore.Qt.Vertical)
        self.progressMatchPeak.setObjectName("progressMatchPeak")
        self.gridLayout.addWidget(self.progressMatchPeak, 4, 9, 3, 1)
        self.checkBoostContrast = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoostContrast.setChecked(True)
        self.checkBoostContrast.setObjectName("checkBoostContrast")
        self.gridLayout.addWidget(self.checkBoostContrast, 2, 3, 1, 2)
        self.imageInput = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageInput.sizePolicy().hasHeightForWidth())
        self.imageInput.setSizePolicy(sizePolicy)
        self.imageInput.setMinimumSize(QtCore.QSize(180, 120))
        self.imageInput.setMaximumSize(QtCore.QSize(180, 120))
        self.imageInput.setToolTip("")
        self.imageInput.setFrameShape(QtWidgets.QFrame.Panel)
        self.imageInput.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageInput.setText("")
        self.imageInput.setScaledContents(False)
        self.imageInput.setAlignment(QtCore.Qt.AlignCenter)
        self.imageInput.setObjectName("imageInput")
        self.gridLayout.addWidget(self.imageInput, 4, 2, 1, 3)
        self.labelMatchThresh = QtWidgets.QLabel(self.centralwidget)
        self.labelMatchThresh.setObjectName("labelMatchThresh")
        self.gridLayout.addWidget(self.labelMatchThresh, 2, 2, 1, 1)
        self.btnOpenInputImage = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenInputImage.sizePolicy().hasHeightForWidth())
        self.btnOpenInputImage.setSizePolicy(sizePolicy)
        self.btnOpenInputImage.setMinimumSize(QtCore.QSize(64, 0))
        self.btnOpenInputImage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnOpenInputImage.setObjectName("btnOpenInputImage")
        self.gridLayout.addWidget(self.btnOpenInputImage, 0, 7, 1, 3)
        self.btnOpenVideo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenVideo.sizePolicy().hasHeightForWidth())
        self.btnOpenVideo.setSizePolicy(sizePolicy)
        self.btnOpenVideo.setMinimumSize(QtCore.QSize(64, 0))
        self.btnOpenVideo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnOpenVideo.setObjectName("btnOpenVideo")
        self.gridLayout.addWidget(self.btnOpenVideo, 1, 7, 1, 3)
        self.btnStartScan = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartScan.setMinimumSize(QtCore.QSize(0, 32))
        self.btnStartScan.setObjectName("btnStartScan")
        self.gridLayout.addWidget(self.btnStartScan, 3, 2, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.labelFPS = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFPS.sizePolicy().hasHeightForWidth())
        self.labelFPS.setSizePolicy(sizePolicy)
        self.labelFPS.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFPS.setFont(font)
        self.labelFPS.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelFPS.setText("")
        self.labelFPS.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFPS.setObjectName("labelFPS")
        self.gridLayout.addWidget(self.labelFPS, 6, 2, 1, 6)
        self.labelFileProgress = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFileProgress.sizePolicy().hasHeightForWidth())
        self.labelFileProgress.setSizePolicy(sizePolicy)
        self.labelFileProgress.setMinimumSize(QtCore.QSize(128, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFileProgress.setFont(font)
        self.labelFileProgress.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelFileProgress.setText("")
        self.labelFileProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFileProgress.setWordWrap(True)
        self.labelFileProgress.setObjectName("labelFileProgress")
        self.gridLayout.addWidget(self.labelFileProgress, 5, 2, 1, 6)
        self.fieldInputImage = QtWidgets.QLineEdit(self.centralwidget)
        self.fieldInputImage.setObjectName("fieldInputImage")
        self.gridLayout.addWidget(self.fieldInputImage, 0, 1, 1, 6)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 8, 1, 1, 9)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.progressBarFiles = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarFiles.setProperty("value", 0)
        self.progressBarFiles.setTextVisible(False)
        self.progressBarFiles.setInvertedAppearance(False)
        self.progressBarFiles.setObjectName("progressBarFiles")
        self.gridLayout.addWidget(self.progressBarFiles, 9, 1, 1, 9)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.setBuddy(self.fieldInputImage)
        self.label_2.setBuddy(self.fieldVideo)
        self.label_3.setBuddy(self.sliderMatchThresh)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FindFrame"))
        self.progressMatch.setToolTip(_translate("MainWindow", "Current matches detected"))
        self.btnResults.setText(_translate("MainWindow", "Results"))
        self.label.setText(_translate("MainWindow", "Input image:"))
        self.label_2.setText(_translate("MainWindow", "Video(s):"))
        self.progressMatchPeak.setToolTip(_translate("MainWindow", "Peak matches detected for file"))
        self.checkBoostContrast.setToolTip(_translate("MainWindow", "Increasing contrast can help with feature detection"))
        self.checkBoostContrast.setText(_translate("MainWindow", "Boost video contrast"))
        self.labelMatchThresh.setText(_translate("MainWindow", "0%"))
        self.btnOpenInputImage.setText(_translate("MainWindow", "..."))
        self.btnOpenVideo.setText(_translate("MainWindow", "..."))
        self.btnStartScan.setText(_translate("MainWindow", "Scan"))
        self.label_3.setText(_translate("MainWindow", "Match threshold:"))
        self.label_4.setText(_translate("MainWindow", "Current video:"))
        self.progressBarFiles.setFormat(_translate("MainWindow", "%v/%m"))
        self.label_5.setText(_translate("MainWindow", "Files:"))
